# GitHub Actions workflow Testing
name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-node-version:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: ['18.19.0', '20.10.0', '21.5.0']

    runs-on: ${{ matrix.os }}       

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies    
      run: npm install

    - run: npm run build --if-present
    
    - run: node -v
